#!/usr/bin/env bash

export AWS_PROFILE
AWS_PROFILE="db-vending-backup"
export AWS_REGION
AWS_REGION="us-east-1"
export AWS_ACCESS_KEY_ID
AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile "${AWS_PROFILE}")
export AWS_SECRET_ACCESS_KEY
AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile "${AWS_PROFILE}")
export AWS_SESSION_TOKEN
AWS_SESSION_TOKEN=$(aws configure get aws_session_token --profile "${AWS_PROFILE}")

lambda_function="${1}"
payload="${2}"

docker run -it --rm \
  -v "$(pwd)/lambda:/var/task:ro,delegated" \
  -e AWS_REGION \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  lambci/lambda:ruby2.7 \
  "${lambda_function}.handler" "${payload}"
